### ISSUE TITLE
Maps for the Stratus Network

### ISSUE THREAD

**Issue by ArmyFrog** [StratusNetwork/Map-Rotations#1]
Hello, I would like to submit these three maps for this server. They have been entirely packaged and are ready to go.
http://www.mediafire.com/file/38s6xckz9ky77hd/ArmyFrog%27s+Maps.rar

**Comment by amactus** [comment]
@ArmyFrog Please add an imgur album with some photos from your maps.

**Comment by amactus** [comment]
Hi, thanks for submitting your maps. I've only looked at Palmetto city and Labritorium so far, and I have some feedback.

Labritorium:
I don't think this map fits our rotations or play style, so at the moment it won't be added. If you were to consider opening it up a bit for more dynamic gameplay, we might consider it.

Palmetto City:
Thanks for your submission! This map works fine, and it looks like it'll play well. I'll add it to the repo and make sure it's tested at some point!

**Comment by amactus** [comment]
I've taken a look at Shoppal Jireleu, and like Labritorium, I don't feel it's the type of map we're interested in at the moment. Possibly in the future.
