### ISSUE TITLE
Midnight Picnic (KotH)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#10]
Midnight Picnic. Revamped for modern OCN. Fixed for modern OCN. Never played on modern OCN. I cri. Enjoy :)

Images: [http://imgur.com/a/tOUAJ](url)

Download: [http://www.mediafire.com/file/g5dkepxav7ysjwv/Midnight_Picnic.zip](url)

**Comment by Palmidence** [comment]
This map I believe is too plain and flat, all things considered. The palette is quite boring and it seems like gameplay would get rather stale.

It looks like four teams: with this size and it being so open, perhaps it needs more cover and more interesting and unique shapes. I feel like the map needs a physical overhaul, but if you have made changes let me know.

**Comment by Palmidence** [comment]
This map was played and people seemed to think it was fun, though it became little stale towards the end. There does need to be more cover though and maybe to make the sides slightly bigger where the hills are so it isn't so easy to knock someone out.

**Comment by Palmidence** [comment]
Can't really do much with it in its current state, sorry.
