### ISSUE TITLE
[CTW/DTM]Ruediger`s Garden

### ISSUE THREAD

**Issue by RuedigerLP** [StratusNetwork/Map-Rotations#100]
Ruediger`s Garden is a two team mixed one wool, one monument map. The map has a gear aspect. Defense materials are collected by digging blocks. The monument has two obsidian blocks to break it faster diamond pickaxes are supplied in the wool rooms. The entire map is block36ed.

Please replace sponge with block36. And chunks are not pruned (sry im to stupid).

[Images](http://imgur.com/a/TNSOY)  
[Download] Private

**Comment by BGMP** [comment]
The map has been tested with the author, and future updates will be handled through the Forums.
