### ISSUE TITLE
Add Coral Reef uno  

### ISSUE THREAD

**Issue by GoldenOre** [StratusNetwork/Map-Rotations#102]
link https://mcresourcepile.github.io/mapstack/overcast?s=coral_reef

quality map

**Comment by Palmidence** [comment]
Already in the repo, please edit your post explaining why you want this change.

**Comment by GoldenOre** [comment]
It's a fine map that was in OCN rotations and is collecting dust atm. Raitings were like 3.67 irc.

**Comment by Palmidence** [comment]
I'll consider this for the next minor rot update in about a week so we can trial it.
