### ISSUE TITLE
[DTC/M] Outcrop

### ISSUE THREAD

**Issue by Ensix** [StratusNetwork/Map-Rotations#104]
### Outcrop

A 12 v. 12 map with one core and one monument on each side and limited resources

[Images](http://imgur.com/a/nIKC4)  
[Download](https://github.com/StratusNetwork/Map-Rotations/files/1133497/Outcrop.zip)

**Comment by Ensix** [comment]
FYI, I fixed a mistake in the XML

**Comment by mitchiiii** [comment]
Unfortunately we wont be adding this map.

First of all, your map is very flat and has minimal above ground coverage or structures besides where there are chests. Greater height variation and structures which can aid in cover and defensive strategies make for a more interesting environment. Mirroring the map with this kind of layout is going to create massive stress towards the far region near the core (I believe it's the core.. the objective directly in front of spawn), and flipping it isn't an option either, so you'll probably end up with something like Desert Cataract.

Having limited resources isn't great for a public rotation, as it becomes quite frustrating late game when your team has no tools left to break the core, or materials to make those tools.

**XML Errors for future reference**
 - Line 48: You don't need to wrap regions in `<region id="..'>..</region>` when simply defining them. `<cuboid id=".." min=".." max=".."/>` is the correct way.
 - You refer to each team by their color -- you must use their `id=".."` which you defined when specifying each team.
 - You are using filter structure for protocol `1.3` -- your team filters should simply be `<team id="only-red>red-team</team>`

However we would like to thank you for your submission and the time you put into making it. Good luck in any future maps you create.
