### ISSUE TITLE
Remove Cairo TDM from rotation

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Map-Rotations#105]
The majority of the map consists of 2-3 block wide corridors, oftentimes being shortened to 1 block at various points throughout the map. Because of this, the map feels extremely cramped, making teamfights look like pointless moshpits where it's difficult to see what's actually going on. Also, due to the fact that a a majority of the map consists of chokepoints, making strafing difficult and bowspamming extremely easy, leaving little room for outplay potential. This video demonstrates my point exactly (video should start at 0:24): https://youtu.be/cRvnfjXAjnw?t=24s

While you could argue that you can fight on the rooftops instead of on the ground, personally I see little reason to do so. First off, the pre-placed ladders to the rooftops are placed in, again, chokepoints, often in 3x3 rooms with 1 block wide entrances. Even if you want to place your own ladders the only real places to due so leave you very vulnerable to knockback. Second, due to the buildings often being fairly small there is little room to navigate for a meaningful melee fight to occur, not to mention that the fences on the rooftops make navigation across several different buildings fairly obnoxious. To the map's credit, the rooftops can make for good archer positions, with fair protection from knockback due to the fences, but to me that isn't enough to overlook the aforementioned issues.

My final issue with the map is the killstreak rewards. At times the order of the rewards don't make sense. At one point your sword gets upgraded to sharp 1 stone and then upgraded to unenchanted iron later on; I'm fairly certain that the former does more dps (correct me if I'm wrong). Also, power bows shouldn't be kill rewards on a map where players spawn with unenchanted leather, especially not with how many chokepoints there are on the map.

**Comment by Palmidence** [comment]
I will be considering this map to be changed in the next minor rot update, which may be in another week to just correct some maps that didn't work out so well (e.g Hanger -> Assault).

Any TDM replacements you can think of for this map?

**Comment by Antnecb** [comment]
TDM specifically or just conquest in general?

**Comment by Palmidence** [comment]
I was thinking TDM since we're trying to keep similar gamemode counts for all rots, but feel free to suggest anything you'd like
