### ISSUE TITLE
Add Curly Wools II to the rotation

### ISSUE THREAD

**Issue by RuedigerLP** [StratusNetwork/Map-Rotations#106]
I think you should add it because so far it always played consistent, never got rushed nor stalemated. And its also a new map and new maps are always good!

**Comment by Palmidence** [comment]
A 4 team CTW to replace one of the BEs would be a great breath of fresh air.

**Comment by RuedigerLP** [comment]
I mean i don't want to be responsible for be2 being removed but its a bit stale anyway.

**Comment by qlados** [comment]
dont remove be2 DD:

**Comment by dragonrider455** [comment]
yeah please dont remove BE2
its fun to defend

**Comment by Ensix** [comment]
I would be okay with BE2 being replaced. It's getting a bit stale imo.

**Comment by Palmidence** [comment]
Maybe in the future, but as it stands with ratings we have not been able to come to a conclusion to add it.
