### ISSUE TITLE
Mansion KotH (Mini) 14v14

### ISSUE THREAD

**Issue by qlados** [StratusNetwork/Map-Rotations#108]
### Mansion
by Valky, Jeremy_Wade and _ArmyFrog
Mansion is a 750 point KotH map with 3 points: Blue Base (1p/s), Red Base (1p/s), Mansion/Mid (1,5p/s). It is suited for the mini-rotation since we decided to make the team size 14v14. There are various tunnels added to make the gameplay not only about mid and to prevent spawncamping additionally to the 5 seconds spawnprotection. 

[Images] http://imgur.com/a/YFzy5
[Download] Contact Poseidons, I sent it to him on discord!

**Comment by mitchiiii** [comment]
This has been in the repo for a while now
