### ISSUE TITLE
Mono (CTW)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#11]
Mono CTW. Fairly old map, although one of my favourites. Never played however, and I wish to change that. TBF it probably is broken But yeah, made for 5v5, simple and concise, good for TE hopefully.

Images: [http://imgur.com/a/8lgd3](url)

Download: [http://www.mediafire.com/file/t1vgp0zs31r1m7u/Mono_TE.zip](url)

**Comment by amactus** [comment]
Currently, this map is too small for public play. If you'd be willing to remake it, we may consider adding it, but as of now, it won't be added.
