### ISSUE TITLE
[DTC/M] CUCKOO

### ISSUE THREAD

**Issue by xSelfie** [StratusNetwork/Map-Rotations#114]
CUCKOO

Mix map DTC/DTM Wet. 2 Teams, 25 players, 5 more overfill, 2 monuments, 1 core, dispensers disabled.
It has a lot of space for cannons to be made.

[Album](http://imgur.com/a/Ht9pp)
[Download](http://www.mediafire.com/file/mth14ggdzdp5dc3/CUCKOO+pub.zip)

**Comment by PoseidonsM** [comment]
Is this for the mapmaking contest?

**Comment by xSelfie** [comment]
What contest

**Comment by PoseidonsM** [comment]
http://stratus.network/destroy-map-competition

**Comment by xSelfie** [comment]
It says that the map has to be dry so no way. So just take it as a normal
application.
