### ISSUE TITLE
Remove Antiquis

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Map-Rotations#115]
Players can take the villagers out of their spots and move / kill them. Since they are used to upgrade pickaxes, killing them can make the match last way longer.

Remove the map until issue is fixed.

**Comment by mitchiiii** [comment]
There was a fix for custom crafting I believe, so https://gitlab.com/stratus/maps/commit/51758b9dd2b5a62f039ba24301ad05f96ceb69b2 just needs to be reverted

**Comment by dragonrider455** [comment]
cant you change it? i think it is already
