### ISSUE TITLE
[DMC] [DTM] Knights Of Osenden

### ISSUE THREAD

**Issue by KnightZack** [StratusNetwork/Map-Rotations#117]
#  **Knights Of Osenden**

Knights Of Osenden is a 3 lane symmetrical DTM style map where teams fight to destroy their opponents monuments first. Two monuments are on each side of the map on the far lanes, and the center monument is inside the center tower. 

[Images]http://imgur.com/a/zsDaG
[Download]https://www.dropbox.com/s/2zcmig599n5aghj/Knights%20of%20Osenden.zip?dl=0

**Comment by dragonrider455** [comment]
can i see better pictures?
