### ISSUE TITLE
[DMC] [DTM] Acropolis

### ISSUE THREAD

**Issue by dragonrider455** [StratusNetwork/Map-Rotations#119]
### Acropolis
![2017-08-09_09 42 39](https://user-images.githubusercontent.com/28639356/29125543-066fef72-7cea-11e7-81c7-7c0b4fa102f3.png)

This is Acropolis.  Several temples are around the map, some housing special weapons or gear.  Defending is needed, since many blocks surround the monument.  You can build in the void.  Iron is located in a temple on the outer path around.  The monuments seem fairly close to one another, but the land route takes about 10 seconds.  Bowing is hard coming right out of spawn, as it is such a long path.  Players should be near the front lines, so i have this as a 24v24.  Right now the map is not at its full potential, but as i am very pressed for time, just barely finishing it with the DL and images and XML as i am leaving for a trip shortly.  I would like to see how well this does, and if it plays decently i will update it to make it better.  Thanks for reading this essay.  Below is a DL link and some images.

[Images]https://imgur.com/a/sEU6f
[Download]https://www.dropbox.com/s/2l1reob93h9fppz/Acropolis.zip?dl=0

**Comment by dragonrider455** [comment]
I am going to update the xml so dont take it yet

**Comment by dragonrider455** [comment]
https://www.dropbox.com/s/14ng3nnpvodn0bm/Acropolis.zip?dl=0
New Download.
XML updated so as to add a quotation mark and a closing tag

**Comment by Palmidence** [comment]
You can submit a request for this to go in rots once its been added and tested a bit.
