### ISSUE TITLE
Orion (DTC)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#12]
2 Team, 4 Core map. Send help to the defenders. But was stolen by Minehut -_- but thats been fixed \o/. So yeah. tnt and all that jazz.

Images: [http://imgur.com/a/Wbotc](url)

Download: [http://www.mediafire.com/file/b3d4hplowna9ym3/Orion_DTC.zip](url)

**Comment by amactus** [comment]
Currently, this map is too small for public play. If you'd be willing to remake it, we may consider adding it, but as of now, it won't be added.
