### ISSUE TITLE
[DMC] Free Fall [DTM]

### ISSUE THREAD

**Issue by dragonrider455** [StratusNetwork/Map-Rotations#122]
### Free Fall

An 8-team map with several layers before descending to the bottom one with the monument.  It is made by Techntross, doing the buillding, and myself doing the XML and some minor building.  Hopefully the XML can actually be done, and i doubt i got it right.  Spawning with a Diamond Pickaxe with efficiency 3 to mine the monument and 4 blocks to protect your self.  Each kill gives 8 more blocks.  Each team has 3 members.  Regen 2 is permanent through the map.

[Images] http://imgur.com/a/RZKAM
[Download]https://www.dropbox.com/s/qtwfkuadvmo1x1l/Free%20Fall.zip?dl=0

**Comment by mitchiiii** [comment]
Can you please explain how this is meant to be played?

**Comment by dragonrider455** [comment]
8 teams compete to destroy one monument
whoever mines the obby wins
