### ISSUE TITLE
[DMC] [DTM] Linked

### ISSUE THREAD

**Issue by qlados** [StratusNetwork/Map-Rotations#125]
### Linked

Linked is a DTM map suited for 18v18 with the monuments being controlled by CPs. It has a futuristic theme and only allows the use of blocks in certain areas. How does the map work now? Well it's pretty easy, you need to cap a point to be able to bridge on that side (on the enemies part of the map) and to break the monument itself. It has many jumppads, staircases and ways to support variety in the gameplay.

[Images] http://imgur.com/a/RnJHy
[Download] private

**Comment by mitchiiii** [comment]
Have you given the download to one of the mapdevs @qlados?

**Comment by qlados** [comment]
I think so @mitchiiii, but i can send it to you too
