### ISSUE TITLE
[DMC][DTC] Diamond Rush DTC

### ISSUE THREAD

**Issue by RuedigerLP** [StratusNetwork/Map-Rotations#127]
Diamond Rush DTC is a 14vs14 DTC. Diamond pickaxes are obtained in a pickaxe room at the enemy's side.

[Images](http://imgur.com/a/LvkYb)  
[Download] Private

**Comment by mitchiiii** [comment]
Have you given the download to one of the mapdevs @RuedigerLP?

**Comment by RuedigerLP** [comment]
@mitchiiii have you received the files?

**Comment by RuedigerLP** [comment]
is there an issue with the map? the maps should actually be play ready, i tested them.
if there is something to fix i can do it so u dont have to waste ur time

**Comment by mitchiiii** [comment]
No, nothing is wrong with the map. There has been some issues with the testing server we've been using which has meant we haven't been able to get this map ready for testing. We hope it will be resolved quickly.
