### ISSUE TITLE
Rogue (DTM/C)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#13]
Rogue, one of my final maps. No prizes for guessing where the name is from, seeing as it was made in December. Inspired by retaliation slightly and Aqealibrius. Enjoy!

Images: [http://imgur.com/a/TlCaJ](url)

Download: [http://www.mediafire.com/file/qcwuwcw2gk2cugq/Rogue.zip](url)

**Comment by amactus** [comment]
Currently, this map is too small for public play. If you'd be willing to remake it, we may consider adding it, but as of now, it won't be added.
