### ISSUE TITLE
[DMC] [DTM] Desert Country DTM

### ISSUE THREAD

**Issue by OCNsOMEN** [StratusNetwork/Map-Rotations#131]
Desert Country DTM is a 16vs16 DTM map that's build in the same style as Desert Country. We used the sand wool sand wool style but didn't copy anything from the original map. We added a 4sec respawn cooldown because the monument is located near the spawn. The obsidian monument changes to gold mode after 10minutes. There is one diamond block in the middle.

[Images] http://imgur.com/a/Gk7ic
[Download] https://www.dropbox.com/s/g34vdemd1vw42ip/Desert%20Country%20DTM.zip?dl=0

**Comment by OCNsOMEN** [comment]
Prizes: The discord tags would go to byRobo and OCNs_OMEN. The strato rank would go to oiskoltaxd (if that's ok) because byrobo and I already have cirro. Stratus- would go to OCNs_OMEN and the stack of tokens would go to byrobo.

**Comment by qlados** [comment]
hey das ist ja meine 2. map :DDDDDDDD
