### ISSUE TITLE
Remove Cold Aunder II from the rotations

### ISSUE THREAD

**Issue by dragonrider455** [StratusNetwork/Map-Rotations#137]
The map almost ALWAYS lasts well into 1 hour, and always results in a skybridge stalemate.  The map isnt that good for ground rushing either.  Its rather plain and the looks are not appealing.  The skybridge will always happen and will become a mess of arrows, shields, and such.  The map gets so block spammed later on, that the lower points are about 6-4 blocks beneath the height limit.  There are random holes everywhere and it is easy just to fall into one, all of the blocks jutting out.  Defenses are always extensively developed, due to the amount of defense materials, and iron efficency pickaxes on stained clay.  Right now the match is going 50 minutes with no touches, or team at an advantage.  Here is a link with some pictures

http://imgur.com/a/XfQzn

**Comment by Matic0B** [comment]
I'd say the map is quite interesting. It might need a few tweaks to solve some of the issues you listed but it shouldn't be removed. With a few less blocks and possibly a higher height limit and less effective pickaxes, it might just be fine.

**Comment by Palmidence** [comment]
The author has quit Minecraft, so he might not be the one to make the changes.

However, height limit is a no because you'll be able to access the whole area above the wool and spawns and everything with the platforms, which was disallowed by both the original and this one. We're going to keep the height limit the same, also increasing it encourages skybridging which we don't want.

Fewer blocks actually will make it more stalematey, you need a good amount of blocks to make a dent in progress getting over there. If you have only 16 glass or something, you'll barely be able to make it there (since it's a lot of void and you can't compensate for the length of the map, despite the amount of blocks scattered making 1x1 holes and such)

I was thinking bumping down pickaxes, which I agree with.

**Comment by Matic0B** [comment]
@Palmidence Reducing the amount of blocks could counter block spam, the height limit could be increased near the middle area slightly but not near the bases, I guess limiting the amount of defensive supplies could be good as well.

**Comment by Palmidence** [comment]
@Matic0B I think dynamic height limits are not the solution to the problem, if anything it'd be more confusing. We'd need a way to visualize it, otherwise you get a bunch of bridgers falling in the void.

I'm also keen on reducing defense supplies.

**Comment by KnightZack** [comment]
Besides the one bug I've heard about (being able to give wool from your woolroom to the other team), I don't think this map should be changed at all. So many maps nowadays are catered towards trying to rush the wool, and having a map that actually requires some level of skill to win shouldn't be punished. The map has a nice aesthetic to it that isn't commonly seen, have a really interesting map layout that is one of the few maps that gives defenders a chance, and all and all makes for some pretty intense battles.

**Comment by Ensix** [comment]
Another problem with the map is that the teams are imbalanced. Blanc spawns with nether bricks and noir spawns with stone bricks. Nether bricks take longer to break than stone bricks and can also be crafted into fences

**Comment by dragonrider455** [comment]
@KnightZack the map doesn't actually look that nice, it may be different, but it doesn't look that nice (the middle islands, nit the steampunk spawn) there needs to be a way to make the map so its not just the skybridge and the 1x1 holes, and the defenses are to good, and then it would be fit for nice, good, entertaining matches.  Fixing all of these would make it a decent map.  The map also doesnt require "skill to win".  If there is a defense with 1-2 defenders, it will be near impossible to get in without a skybridge.  Skybridge battles are not fun imo

**Comment by Palmidence** [comment]
@Ensix Definitely, I'll have to fix that. I had no idea that the spawnkits were unbalanced.

I think this is headed to removal, I'll let a few more comments run through before it's completely removed.

**Comment by dragonrider455** [comment]
@Palmidence removal? like the map from the rotation or the issue?

**Comment by Palmidence** [comment]
@dragonrider455 The rotation.
