### ISSUE TITLE
Remove Nar

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Map-Rotations#138]
Due to all of the issues that need to be worked on, remove the map until it gets updated.

Possible maps to replace it:
 - Cyril
 - Jactus
 - Thunder
 - Thundershock
 - Thunderstorm
 - Watchtower
 - Quench
 - Uchiura

**Comment by dragonrider455** [comment]
I was about to create this.  If you need a list of issues, ask.

**Comment by Palmidence** [comment]
List some more map replacements if you can and I'll be sure to replace it

**Comment by Matic0B** [comment]
@Palmidence Went through the CTW repo and looked at team sizes for maps, added a couple more possible replacements.
