### ISSUE TITLE
Trail Mix (CTW)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#14]
Ayy! The final one, for the moment. 8v8 CTW, 2 Wools, limited Iron and more fun then anyone could ask for! Hope you enjoy!

Images: [http://imgur.com/a/YP1B6](url)

Download: [http://www.mediafire.com/file/u2buprms7bumifm/Trail_Mix.zip](url)

**Comment by amactus** [comment]
This was tested during our weekend event, and seems to be working fine. I've not had a chance to look at the gameplay in any detail, but unless I find any issue, this map will now dwell in the repository!
