### ISSUE TITLE
[CTF] Divided

### ISSUE THREAD

**Issue by Diamyx** [StratusNetwork/Map-Rotations#141]
Divided

this map was on OCN but didn't get moved over for some reason please fix

[Images](http://imgur.com/a/3EL2O) (some are a bit outdated but it's ok)
[Download](http://www.mediafire.com/file/b6jfjd5sch3elok/Divided.zip)

**Comment by sausage191181** [comment]
Should be all good, I'll download it and check it all when I'm home.
