### ISSUE TITLE
[CTW] Autumn in Kiev

### ISSUE THREAD

**Issue by Hudsonlovestech** [StratusNetwork/Map-Rotations#142]
**Autumn in Kiev** _by shadowxdark and Sydiem_
![autumn-in-kiev](https://user-images.githubusercontent.com/28578738/32140971-a35703ae-bc49-11e7-8f9f-f33457de366a.jpg)
Autumn in Kiev is a 12v12 mini CTW map created for Stratus Network. Each team must capture the other team's wool and return it to their objective point. First team to capture the wool wins.
[**Images**](https://imgur.com/a/Wj2Tl)
[**Download**](https://www.dropbox.com/s/8j6l1179z8efga2/autumn_in_kiev.zip?dl=0)

**Comment by Matic0B** [comment]
Map submissions are now handled through our [Submissions](https://stratus.network/forums/59ac44b7a2e3a9000100004b) forums.
