### ISSUE TITLE
Core on Retaliation 2 has only 1-2 blocks of lava

### ISSUE THREAD

**Issue by amactus** [StratusNetwork/Map-Rotations#16]
I doubt it used to work like that, you have to mine at least 3 obsidian blocks to make it leak.

- 2000thehecf1

**Comment by mitchiiii** [comment]
I don't think it has changed at all. Retaliation's core isn't as thick as Retaliation 2, which is probably where the confusing is coming from.

**Comment by amactus** [comment]
Out of personal interest, I took a look at this, and it is very odd that you need to break between 3 and 4 obsidian to leak the core. I'll change this

**Comment by Palmidence** [comment]
This has been changed. :)
