### ISSUE TITLE
Quench (CTW)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#19]
CTW that I've made for this server. 24 v 24. 1 wool per team but 2 entrances. Enjoy!

**Links**

[Images](http://imgur.com/a/652UE)

[Download](http://www.mediafire.com/file/1gx5xe044l01016/Quench.zip)

Contact: Obelistics#0494

**Comment by amactus** [comment]
Hi, I really like the look of your map, but it has some major XML issues which doesn't allow it to load. Please see if you can fix these, and if not, I can provide assistance.

![screen shot 2017-02-10 at 10 22 19 pm](https://cloud.githubusercontent.com/assets/12880908/22851733/132373f2-efe0-11e6-8de3-613a8915c73e.png)

**Comment by sausage191181** [comment]
**Update**

Fixed regions
Fixed Red team colour
Fixed wool locations

[Download](http://www.mediafire.com/file/1gx5xe044l01016/Quench.zip)

**Comment by amactus** [comment]
Good job fixing those, but apparently that's created a bunch of new issues. Again, if you need help, do ask

![screen shot 2017-02-11 at 6 31 25 pm](https://cloud.githubusercontent.com/assets/12880908/22859189/673fc21c-f088-11e6-83b9-6792cfac8c34.png)

**Comment by Palmidence** [comment]
Fixed the XML, regions and everything seems to work! Added.

**Comment by cswhite2000** [comment]
I noticed that both the red and the blue teams have red hardened clay in their supply chests.

**Comment by sausage191181** [comment]
Thanks for the heads up! I must've forgotten to change the chests 0.o XD
