### ISSUE TITLE
Aqeabrilius (CTW)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#2]
Here is a map which I had for OCN, but seeing as it might go well in here, here it is. Aqueabrilius - made a while back but still works 0.o

Images: [http://imgur.com/a/ITEMF](url)

Download: [http://www.mediafire.com/file/jplfce3ujqt4ms5/Aquealibrius.zip](url)

**Comment by amactus** [comment]
This has finally been tested, and it looks good. Added!
