### ISSUE TITLE
The Wonders of the World (Rush)

### ISSUE THREAD

**Issue by JexeI** [StratusNetwork/Map-Rotations#21]
### The Wonders of the World

This is the community rush map 3: the wonders of the world. I can't find the archive to this map thread on oc.tc, rip

[Download]Private
I dm'd this to you a week ago shiny and you still didn't load it :v

**Comment by amactus** [comment]
That's because shiny is busy being a dev, and not doing mapdev stuff. DM me the download

**Comment by amactus** [comment]
Thank you for your submission. This map will be added to the repository soon
