### ISSUE TITLE
Clay Clay Wars (DTC/Blitz)

### ISSUE THREAD

**Issue by cswhite2000** [StratusNetwork/Map-Rotations#22]
Clay Clay Wars is a 100 vs 100 War Wars inspired DTC/Blitz map.

Images: https://imgur.com/a/lKy2D
Map Download: https://drive.google.com/file/d/0B8Gx8lM_WMbsakdyMGNxcDdHRzA/view?usp=sharing

**Comment by Palmidence** [comment]
I think we're focused more on serious submissions right now

**Comment by amactus** [comment]
I'll point out that I actually loaded this, so it's in the repo now

(shh)
