### ISSUE TITLE
Deepwind Jungle and Wooly Woods

### ISSUE THREAD

**Issue by cswhite2000** [StratusNetwork/Map-Rotations#23]
In Deepwind Jungle players can build adjacent to spawn, where the shouldn't be able to.
Image: https://i.imgur.com/svtFyEl.png

In Wooly Woods the back wall of red spawn can be broken by both teams, while the back wall of blue spawn can be broken by neither team.

**Comment by Palmidence** [comment]
Please make a separate issue for each bug.
