### ISSUE TITLE
Deepwind Jungle: Players can build adjacent to spawn.

### ISSUE THREAD

**Issue by cswhite2000** [StratusNetwork/Map-Rotations#24]
Players can build adjacent to spawn where they shouldn't be able to.
Image: https://i.imgur.com/svtFyEl.png

**Comment by Palmidence** [comment]
What exactly makes this unintentional? Is it not possible on the other side, does it break gameplay, or is the other team not able to?

If it's just spare ground by spawn, it's probably not really that much of a "bug" per se.
