### ISSUE TITLE
Add Coral Reef II 

### ISSUE THREAD

**Issue by GoldenOre** [StratusNetwork/Map-Rotations#27]
You know you wanna you know you gotta you know you will

**Comment by Palmidence** [comment]
Reasonnssss?

**Comment by GoldenOre** [comment]
Its a great map! Gameplay is amazing aesthetics are slick and  it has a community rating of 5/5. You can also farm lots of lanas

**Comment by triplezko** [comment]
Good map. Claf's favorite map during KFC.

**Comment by Palmidence** [comment]
Got some feedback from others, not going to happen, sorry.

**Comment by GoldenOre** [comment]
"others" who???? And what are the issues with this 5/5 map??

**Comment by Palmidence** [comment]
Check Discord, and if you want more opinions feel free to gather some in #mapmaking.
