### ISSUE TITLE
Arabian Nightmare (TDM)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#3]
My first released map - Arabian Nightmare, by Kroest and myself

Images: [http://imgur.com/a/vfVrd](url)

Download: [http://www.mediafire.com/file/q2swcxng5jwh0re/Arabian_Nightmare.zip](url)

**Comment by Palmidence** [comment]
This map is very design-heavy and if I recall, it was a really narrow map. I would suggest expanding it, and making it less restrictive with the fences and whatnot for better gameplay.

Just some feedback.

**Comment by sausage191181** [comment]
Ok, Thanks alot! I'll see what I can do!

**Comment by Palmidence** [comment]
We did an official test of this map, and there were the following errors:
- Scoring did not work (the match was at 0 points the whole time)
- People thought that navigation was too confusing
- People thought that the map was too laggy (subjective)

Along with my previous feedback of it being pretty narrow, the map was mixed with likes and dislikes overall. I'd work on expansion and restriction first over everything, then we'll work from there.

**Comment by sausage191181** [comment]
Ok cool!

**Comment by Palmidence** [comment]
Considering the large amount of changes required for this map to be accepted, I'll close it. You may create a new submission that addresses all of the concerns, and go from there.
