### ISSUE TITLE
[Water Drop]  Water Drop II

### ISSUE THREAD

**Issue by Flashee** [StratusNetwork/Map-Rotations#31]
### Water Drop II

Second edition to my first map, Water Drop.  It has the same look to it.

 [Download](https://www.dropbox.com/s/mwvqthjn3wed1cb/Water%20Drop%20II%201.0.zip?dl=0)
[Images](http://imgur.com/a/0FEkv)

**Comment by Palmidence** [comment]
Images please.

**Comment by Flashee** [comment]
Do I really need them tho...?  There is nothing special about it.  It's a /sn map.  If so, I guess I can take them...

**Comment by Palmidence** [comment]
Every submission needs to follow the standards.

**Comment by Flashee** [comment]
Updated.

**Comment by Flashee** [comment]
So now what?

**Comment by Palmidence** [comment]
Be patient for your map to get a response. 3 hours isn't enough to go through all of the works and have it on the main server: currently, it can't be tested due to the map development server being down at this time.

**Comment by Palmidence** [comment]
Hey, can you try to format the XML so there's no tabs mixed with spaces? Try to follow other XMLs for conventions. https://github.com/OvercastNetwork/maps.oc.tc/

It also won't set.

**Comment by Flashee** [comment]
Thanks for telling me.  I had no idea there were spaces (I didn't make the XML).  Fixed it all up though. Here is Water Drop II's fixed download: https://drive.google.com/open?id=0BwYqxATpTWBkZUFpREZleS1qbzA

And here is Water Drop's fixed XML: https://drive.google.com/open?id=0BwYqxATpTWBkdVdqSlhoczF5QjQ

**Comment by amactus** [comment]
I tested this, and it's throwing multiple PGM errors. Please check that your world isn't corrupted, and that everything is working as it should. When done, make a new issue.

**Comment by Flashee** [comment]
Sorry to bother but that's vague.  What exactly are the errors?  And how would I see if a world is corrupted?  Thanks.

**Comment by amactus** [comment]
@Flashee check if you can a) load the map, b) if there are any missing chunks etc. and c) the XML is working properly
