### ISSUE TITLE
[Water Drop] Water Drop (Fix)

### ISSUE THREAD

**Issue by Flashee** [StratusNetwork/Map-Rotations#33]
### Water Drop

This is an XML fix for my map Water Drop.  It's been played many many times already!

[Images] The map is already loaded and has been played a lot.
[Download](https://drive.google.com/open?id=0BwYqxATpTWBkdVdqSlhoczF5QjQ)

**Comment by lordcreeper01** [comment]
Please make only 1 issue per map , and update the issue as you update the map

**Comment by lordcreeper01** [comment]
https://github.com/StratusNetwork/Map-Rotations/issues/31

**Comment by Flashee** [comment]
... This is the only issue for Water Drop.  What are you talking about?

**Comment by Flashee** [comment]
Water drop is a different map from Water Drop II hence the _**II**_ after the title...

**Comment by lordcreeper01** [comment]
My bad

**Comment by Flashee** [comment]
Ok, it's fine.

**Comment by amactus** [comment]
Thanks. Will be uploaded when the time is nigh
