### ISSUE TITLE
[DTM] Team Grief

### ISSUE THREAD

**Issue by pikpikpikpikpikpikpikpik** [StratusNetwork/Map-Rotations#35]
[DTM] Team Grief

8v8
Two Lives
much fun

A map where the objective is to completely destroy (90% of) your own side!

Players spawn with 3 stacks TNT and a fishing rod that spawns Primed TNT.

Also some tools.

More can be seen in the album below.

The map has been tested in PGM and 100% works as intended.

[Images]http://imgur.com/a/F8MXW 
[Download]: Sent to amactus

**Comment by amactus** [comment]
FunFunFunFun but nah. I'll keep it in our secondary folder for another day
