### ISSUE TITLE
[CTW] Wooly Wools

### ISSUE THREAD

**Issue by pikpikpikpikpikpikpikpik** [StratusNetwork/Map-Rotations#36]
[CTW] Wooly Wools

Imagine a tower, made entirely of wool, where each floor has a different kind of special wool, and whomever combines these wools would attain god-like power.

This is the setting for Wooly Wools - a ridiculous CTW by pikpikpikpik and BGMP00.

Ok for real it's an 8v8 where people start on the top floor of the tower and must make their way to the bottom. Also, TNT is involved. Many will die on this map.

This map has been tested in PGM and (somehow) it works just fine.

The best way to make sense of this map is by looking at it yourself.

[Images] http://imgur.com/a/l3rZ3
[Download] Sent to amactus.

**Comment by amactus** [comment]
No. Fun maps are good, but I feel this takes it a little too far
