### ISSUE TITLE
[DTM/Arcade] Banshee Gardens

### ISSUE THREAD

**Issue by BGMP** [StratusNetwork/Map-Rotations#37]
### Banshee Gardens

A 3v3 Arcade map. You spawn on your side (your garden) and the objective is to destroy a 90% of the other team's garden using the tools that the map provides you, which are:

- A _Cannon Stick_, a stick that fires TNT.
- And a _Banshee Souls Gun_, a blaze rod that fires Wither Skulls.
- You also have a double jump that recharges on landing.
- I modified the spawn system because there was a glitch that allowed players to destroy their own monument during the last three seconds of the countdown.

Images: [Map Album](http://imgur.com/a/CKMuI)
Download: I prefer to keep it private.

**Comment by pikpikpikpikpikpikpikpik** [comment]
My name is pikpikpikpik and I approve this map

**Comment by OnlyAndJustMe** [comment]
It looks very cool!

**Comment by PotatoStealer** [comment]
Cool map!

**Comment by amactus** [comment]
Seems like a fun setnext map for times where there are few players, don't see why not.
