### ISSUE TITLE
Add Arch [Submission]

### ISSUE THREAD

**Issue by DowlyMC** [StratusNetwork/Map-Rotations#38]
Arch was added to the rotation just before ocn closed down.

Here are the files, in .zip: https://www.dropbox.com/s/17w13h6fvshzkme/Arch%201.0.12.zip?dl=0

**Comment by amactus** [comment]
@DowlyMC Mediafire links aren't allowed. Please use dropbox or google drive

**Comment by DowlyMC** [comment]
Dropbox: https://www.dropbox.com/s/17w13h6fvshzkme/Arch%201.0.12.zip?dl=0

**Comment by amactus** [comment]
This is more of a submission, did you make this map?

**Comment by DowlyMC** [comment]
Yes, I made it

**Comment by amactus** [comment]
Hi, I've taken a proper look at your map, here's some feedback:

I love the aesthetics, and the use of a monument and woolrooms. I'm interested to see how the gameplay works out. However, there are some issues I've noticed:

- Players currently spawn outside of their spawn houses
- The wool victory monuments are defined in the wrong locations in the XML
- The victory monuments are in a region which blocks wool placement, making winning impossible

If you could work to fix these changes, we can get the map tested and then added!

**Comment by DowlyMC** [comment]
https://www.dropbox.com/s/qg6vv9aunbq2uoc/Arch%201.0.13.zip?dl=0

There, it should work now.

Turns out I had an older XML version paired with the newest map design :P

**Comment by DowlyMC** [comment]
Has it been added yet?

**Comment by amactus** [comment]
No, you would have been told if it had. We've been having issues with our mapdev server, so map addition is currently halted.

**Comment by amactus** [comment]
Okay, thanks for your changes. Arch has now been added to the repo!
