### ISSUE TITLE
Add enchanted axes to GD III.V

### ISSUE THREAD

**Issue by Listegerade** [StratusNetwork/Map-Rotations#39]
So when you try to craft a golden axe the outcome would be Unbreaking III golden axe instead.

**Comment by Palmidence** [comment]
I do agree that some form of unbreaking on axes would be beneficial for defenders. I've seen myself having to craft numerous axes in the past.

**Comment by BGMP** [comment]
I agree with this idea as well, mainly because it'd make defending easier and I think unbreaking III would do good for the axes.

*This is working for me, I don't have Golden Grought III.V's XML, so, I hope you can add it:*
```
<crafting>
    <shaped override="true">
	    <ingredient symbol="G">gold ingot</ingredient>
        <ingredient symbol="S">stick</ingredient>
        <shape>
            <row>GG.</row>
            <row>GS.</row>
            <row>.S.</row>
        </shape>
	<result material="gold axe">
            <enchantment level="3">durability</enchantment>
        </result>
    </shaped>
</crafting>
```

**Comment by amactus** [comment]
@BGMP Could you possibly add to the XML so you can craft axes in the other direction?

x a a
x o a
x o x

where x = air, a = gold and o = stick

If you could do this, that would be great

**Comment by Palmidence** [comment]
@amactus 

```
<crafting>
    <shaped override="true">
	<ingredient symbol="G">gold ingot</ingredient>
        <ingredient symbol="S">stick</ingredient>
        <shape>
            <row>GG.</row>
            <row>GS.</row>
            <row>.S.</row>
        </shape>
	<result material="gold axe">
            <enchantment level="3">durability</enchantment>
        </result>
    </shaped>
    <shaped override="true">
	<ingredient symbol="G">gold ingot</ingredient>
        <ingredient symbol="S">stick</ingredient>
        <shape>
            <row>.GG</row>
            <row>.SG</row>
            <row>.S.</row>
        </shape>
	<result material="gold axe">
            <enchantment level="3">durability</enchantment>
        </result>
    </shaped>
</crafting>
```

**Comment by BGMP** [comment]
Wait, when overriding a craft that already exists, it also takes the other possibile ways to perform it, so, when I said I tested it's because it also works to the other side, without having to add a second recipe. 
@Palmidence test it only adding the fragment of XML I sent and you'll see that covers the two possible crafting recepies for the gold axe.

**Comment by Palmidence** [comment]
@BGMP Ah, my bad. I'll go ahead and do yours.

**Comment by amactus** [comment]
I've added this, although it won't be live until a small region change is made.
