### ISSUE TITLE
[DTM/CTW] Netherwatch

### ISSUE THREAD

**Issue by jman2** [StratusNetwork/Map-Rotations#40]
[DTM/CTW] Netherwatch

A 3x3x3 Bone Block monument that can be repaired by a block after 4 kills, and a single wool to capture.

http://imgur.com/a/fRVPq
https://drive.google.com/open?id=0BzVL1A_olpTja2tVTFY3MDU2dlk (EDITED)

EDIT:

Thanks to _3Each, I now know that players can connect even when in 1.9, meaning they won't see 1.10-1.10-2 blocks, including bone blocks and shulker boxes, both of which are in this map. While not as stylish I've replaced bone blocks with nether brick in the map and xml, and replaced shulker boxes with chests/droppers. Because of the change from bone blocks to nether brick I'm changing the map name to Netherwatch.

http://imgur.com/a/4rpsW

**Comment by Palmidence** [comment]
XML needs some work, I see quite a few errors there. I also don't think 81 region files are necessary, so try to reduce that down a bit. If you haven't already, prune your map with MCEdit. If you also are changing the map name, feel free to reflect it in the GitHub submission. Map.png is also wrong format, but I can go ahead and fix that for you.

Map looks great, it's cute and I'd like to test it: hopefully it's not too small, though. I don't think this will be able to hold 24+ players.

**Comment by amactus** [comment]
No response from @jman2. Open a new issue if you want to continue
