### ISSUE TITLE
[CTW] The First Crusade

### ISSUE THREAD

**Issue by EthanMcFarlin** [StratusNetwork/Map-Rotations#41]
**[CTW] The First Crusade v1.2.2**

**Description**
The First Crusade is a 32-64 player Capture the Wool conquest, with a medieval themed building style. Players are challenged to capture the wool from the enemy team and return it to their place zone. 

**Gallery**
Main Spawn Island (Outer View): http://imgur.com/a/o3TdX
Main Spawn Island (Inner View): http://imgur.com/a/goeBI
Battle Zone: http://imgur.com/a/nXwF7
Wool Room: http://imgur.com/a/nYip6
Void Space: http://imgur.com/a/6o4fQ
Aerial View: http://imgur.com/a/cf02J

**Development**
I originally developed the map with Tigo, a server moderator, on Lifeboat PC, but with its closure, map development came to a halt. I have now picked progress back up, and have tied up its loose ends.

**Opportunity**
Adding the map to the server's rotation would not only pay homage to our hard work, but would also usher in the release of Stratus with a new map to sport the server's uniqueness. Through our many tests and extensive fine-tuning, I am confident that The First Crusade would be a welcome addition to the Stratus rotation and its large capacity would be well suited for server growth.

**Download**
Google Drive: https://drive.google.com/file/d/0Bz49vlkHqg29SURZY3M0UkFxRVE/view?usp=sharing

**Contact**
Email: ethanmcfarlin2@gmail.com
Discord: SrNativee
Skype: ethan.mcfarlin

**Comment by Palmidence** [comment]
I like the effort that went into this post! Thank you for the submission, I'll be sure to look at it in detail later.

**Comment by EthanMcFarlin** [comment]
Still waiting on a response...

**Comment by Palmidence** [comment]
Sorry for the long response! You may feel free to PM me on Discord or ping me here if the response exceeds longer than you think it should. In my case, about a week.

Anyways, I have seen the map and it leaves a good first impression. I would suggest the following changes:

- Remove the cobwebs in the battlefield, getting stuck on them while trying to combat the enemy is inconvenient and can be annoying if they're not placed strategically.

- Remove the randomized fire in the battlefield, that may pose an issue if users have wooden materials and I see more deaths arising from stepping in fire scattered around the map then an enemy knocking them into it.

- Lessen the amount of redstone. People cannot place blocks on redstone and having random spots where people try to escape via blockspamming or other conventional methods may feel that it is unfair there are spots where they'd not be able to build unless they broke it.

- There are a lot of region files. If you haven't already, I'd also prune your map (see MCEdit) and refer to https://docs.oc.tc/guides/packaging/pruning_chunks 

XML seems fine at first glance, ran it through a validator and it's happy, so I wouldn't worry about that until it can be loaded and tested. I am interested in testing it.

By the way, it seems like the map testing server may still be down, but once it can be tested thoroughly you might see it in the server. Try making these changes in the meantime.

**Comment by EthanMcFarlin** [comment]
Has the map been tested yet? If not, I'd be willing to offer up my own PGM server for testing purposes.

**Comment by Palmidence** [comment]
Just so you know, it's been loaded on the testing server :) it will be tested soon.

**Comment by Palmidence** [comment]
I already mentioned fixing the XML with you, but I'll try to have it by Tuesday.

**Positions:**
red spawn: 81, 0, 977 width=25 height=42
red bridge: 83, 0, 998 ||| 87, 28, 1032

blue spawn: 81, 18, 1246 width=25 height=42
blue bridge: 75, 18, 1225 ||| 79, 28, 1191

magenta: 79, 23, 1231

- Convert cuboids to circles/cylinders
- Swap magenta spot with cyan spot
- Lower height limit(?)

**Comment by Palmidence** [comment]
I was adding it, but you forgot to add wool monuments (or at least I can't find them...) the coordinates for them are to the left and right of spawn, but in place are just slabs that you can't interact with. PM me a new download, since I already have the fixed XML in your Discord DMs.
