### ISSUE TITLE
Warlock's void issue

### ISSUE THREAD

**Issue by BGMP** [StratusNetwork/Map-Rotations#42]
Well, this has been a problem in Warlock for a while, and I saw it happening today.. it was something like this:

![2017-03-10_23 31 07](https://cloud.githubusercontent.com/assets/26081543/23820860/8cdccfe4-05f8-11e7-8834-a518e3959cf6.png)

I added a void region to the xml and it works for me.. just adding the following code into the regions module:

```
<union name="void">
	<rectangle min="119.5,-48.5" max="23.5,-48.5"/>
	<rectangle min="23.5,-47.5" max="23.5,47.5"/>
	<rectangle min="23.5,49.5" max="119.5,49.5"/>
	<rectangle min="119.5,47.5" max="119.5,-47.5"/>
</union>
<apply block="deny-all" message="You may not edit the void area" region="void"/>
```
Here's the full [XML](http://pastebin.com/tH5ThKBg) with the change implemented.

**Comment by mitchiiii** [comment]
https://github.com/StratusNetwork/Map-Rotations/issues/17
https://github.com/OvercastNetwork/Issues/issues/1493

> After speaking with both map makers they consider this a feature and not a bug
