### ISSUE TITLE
[KotH] Antaran

### ISSUE THREAD

**Issue by ArmyFrog** [StratusNetwork/Map-Rotations#45]
### Antaran

Antaran is a King of the Hill map featuring five points, all of which must be captured in order to win the game. There is a spawn chute at the far end of the map that leads into a Japanese themed rocky mountain-like area with sakura trees. This area contains one control point, the closest one to the spawn and is initially controlled by the respective team. The path in the mountain area leads straight into a large structure containing the second team controlled point. This structure goes right into center building containing the center point. Aesthetically, the entire map has a very traditional Japanese theme, with rocky bluffs, sakura trees, and themed buildings. I hope you enjoy it.

[Album](http://imgur.com/a/LIvWX)  
[Download](https://www.mediafire.com/?plc1qn5ai63kic3)

**Comment by Palmidence** [comment]
May I have a non-mediafire upload and an overview image, please? Also, information like player count, spawnkit, and other features may help us judge it better, so try to cram those in :)

I like KoTH maps with 5 points, they're my favorites, and you have a really nice theme so you're on the right track :) Once I get info like player count & other specs, I'll be able to give more feedback.

**Comment by ArmyFrog** [comment]
The xml is all messed up, I am working on fixing it, so I will do so once its done.

**Comment by bryanowen7** [comment]
Hi, I'm LeapingSpider, I just helped ArmyFrog testing his map, since it was my server I have the xml, he asked me to upload it to you since he will not be online tomorrow.

[XML Link](https://pastebin.com/1evuiPfN)

Thank you.

**Comment by ArmyFrog** [comment]
Thanks, I appreciate it.

**Comment by ArmyFrog** [comment]
I forgot to get the chunks pruned. I need to do that, and at barriers to a certain spot to avoid letting players to take a route they shouldn't.

**Comment by ArmyFrog** [comment]
[Antaran.zip](https://github.com/StratusNetwork/Map-Rotations/files/929796/Antaran.zip)
Alrighty, the map is all done.

**Comment by lordcreeper01** [comment]
Hi! 
Sorry for the delay on the response, I have to say that at his current state the map is playable however I would prefer to have some gameplay issues fixed first so the map plays smoothly, as the map currently is capturing the 5 control points is almost imposible as the last hill being just out of the other team spawn makes it stalemate, I suggest to have some way of conditional portals or spawns , also I would set a time limit.

Cheers!

**Comment by ArmyFrog** [comment]
Hello, thanks for the response, I would like to thank you for taking a look at the map. I will take your tips into consideration.

**Comment by Palmidence** [comment]
Hey,

I'd recommend taking what @lordcreeper01 said into consideration. Again, I like the map, but the last hill is a key component of the gameplay and it's important that it's reasonably obtainable. You may feel free to look at other maps that tackle hills close to spawn (increasing timer, condition portals, different spawn locations) rather than have to go out of the way and change the map physically.

Also, for future reference, try to include an overview image. I'll be keeping this open provided you make the changes within the next few weeks.
