### ISSUE TITLE
[Koth] (Tnt) The Lost Light in the Darkness

### ISSUE THREAD

**Issue by XxAngelRavenxX** [StratusNetwork/Map-Rotations#46]
Your team must be the one with more players in the hill zonein order to control it. You must protect the lCaptured Hills `rto keep increasing yourteam score and win the match.

Team size:16/16
Map Status: Complete
More Pictures and Kits: http://imgur.com/a/7smq4
Trailer Map: https://www.youtube.com/watch?v=ew937ebtw8U
Map download: https://www.dropbox.com/sh/l1fw1lkk8l5ldnr/AADKXxCItNETXU8rL76Be73Da?dl=0

**Comment by lordcreeper01** [comment]
This map look pretty good! I will take a look at it when posible, thanks for submitting!

**Comment by lordcreeper01** [comment]
Hi after taking a look in game I notice a mayor problem with gameplay, the middle hill is only accesible by 2 paths which makes it almost imposible to players to recover the middle hill once its been capped once, adding more paths to the middle hill will greatly improve gameplay

**Comment by Palmidence** [comment]
Since the author has not given a response and this was posted March 30th, with a map developer response 22 days ago, I will be closing this for now. Please comment with a response to @lordcreeper01 before requesting this to be reopened.
