### ISSUE TITLE
[CTF] Lost Civilization

### ISSUE THREAD

**Issue by XxAngelRavenxX** [StratusNetwork/Map-Rotations#48]
[Ctf] Lost Civilization

Capture the flag. The team that reaches 330 points, wins

Team size: 16/16
Map Status: Complete
Trailer Map: https://www.youtube.com/watch?v=2eMeqaEQ3_4
Map Download: https://www.dropbox.com/sh/dzkz5gseyz8wj39/AAAsmZx59fGN8gj7UvjmAF4pa?dl=0
More Pictures and Kits:http://imgur.com/a/SCBFB

**Comment by BGMP** [comment]
The map itself is correct, and even tho there's some plane areas, there's some other spots which really help to complement them, so, in general it looks fairly good for managing a fluent gameplay. In terms of XML, it works properly. Has been added to the repo.

~ El mapa en sí es correcto y, aunque tenga ciertas zonas llanas, exísten otras que ayudan a complementarlas. Así que en general es apto para manejar partidas con la cantidad de jugadores para la cual fue diseñado. El XML por su parte también es correcto. El mapa ha sido añadido al repositorio.
