### ISSUE TITLE
Troopa [Avoid the arrows]

### ISSUE THREAD

**Issue by FuriosoD1** [StratusNetwork/Map-Rotations#49]
Troopa is a map where there are two teams:

Archers: These players have an arch with explosive arrows.
Runners: These players have to avoid the explosive arrows.

Important things of the map:

1. The map is 5 minutes and the runners have 5 minutes to avoid the arrows and the archers have to kill all runners in 5 minutes. If all runners die, archers win the match but if all runners don't die, they win the match.

2. Runners have No-Fall but Archers don't have it because they can jump to the Runners base and if an archer jump to the Runners base, he will die.

3. All players have no regeneration.

4. Hunger is disabled.

5. All players have Infinite Glowing and Speed 2.

6. Runners have Resistance during the first 6 seconds.

7. All players have 1 life.

The most important thing:

I couldn't test the map because PGM doesn't work in my scrimmage server. I mean that I don't know if the map is well configured.

Downloads:

Images: http://imgur.com/a/4yQPq
Map + Xml: https://www.dropbox.com/s/qg4rkh9e8hnmc01/Troopa.rar?dl=0

**Comment by amactus** [comment]
In it's current state, this will not be loaded. There is way too much lava surrounding the map, and I know you'd like that as a feature, but at the moment it's just a lag machine.

Focus on making the other sphere look more aesthetic, and maybe use a red-colored block, not lava
