### ISSUE TITLE
[CTW]CurlyWools

### ISSUE THREAD

**Issue by RuedigerLP** [StratusNetwork/Map-Rotations#50]
CurlyWools is a two team ctw map intended for 32vs.32 players, one wool for each team to cap. 
There is also a gear aspect, for 15 emeralds (killrevard or 5% drop chance from blocks) you can buy diamond helmet/boots with +5 heart attribute or a power bow. Iron can be found in the base and defensive materials at the wool room. This map is supposed to be funny to defend and to have big sky bridge fights.

[Images](http://imgur.com/a/LirCJ)  
Download (private)

**Comment by amactus** [comment]
Hi, could I get your discord name so you can DM me a download?

**Comment by BGMP** [comment]
The map was tested and played in public matches and it works quite nice. Has been added to the repo!
