### ISSUE TITLE
Gamemmo HG2 (Hunger Games Map)

### ISSUE THREAD

**Issue by FuriosoD1** [StratusNetwork/Map-Rotations#51]
Formerly, there was a server called "Gamemmo". That server was about Hunger Games and it was unique. I miss that server and I decided recreate one map that was in that server.

Map + XML: https://www.dropbox.com/s/ojsqm4awnukjuzd/Gamemmo%20HG2.zip?dl=0
Images: http://imgur.com/a/Bl4sx

**Comment by Palmidence** [comment]
Hey,

I have removed a link that led to the server video. I don't think we're currently interested in developing Hunger Games and furthermore, if we do we'll be striving to have more original content. Your recreation isn't in our interests right now, but we'll let everyone know if there's a demand for a certain type of map in the future.
