### ISSUE TITLE
[CTW] Uchiura

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Map-Rotations#55]
Yousoro~ Welcome to my second map, and my first attempt at an objective map, Uchiura. This map is inspired by the setting of _Love Live! Sunshine!!_, which is based off of the real life Numazu, Shizouka Prefecture, Japan. Many of the structures of the map are based off of locations from the anime. My goal for this map was to give it a more natural shape to it, rather than the well-defined shapes seen in most CTW maps (although I had to sacrifice this goal somewhat in order to make the map less rushable). For the wool locations, I went with a design similar to Connected, where the opposing team's wool rooms are on the same piece of land, although with the area connecting them being inaccessible. I did this to  allow players to see their team's wool rooms clearly from right outside of spawn, seeing as the wool rooms would be much less visible if they were directly to the side of spawn. 

![2017-04-20_14 03 45](https://cloud.githubusercontent.com/assets/26776253/25250469/b6586b34-25e3-11e7-8536-e533808a4972.png)

Team size: 24v24
Teams: Pink vs Light Blue

Album: http://imgur.com/a/g4GaB
XML: https://pastebin.com/d4t6VBnK (may need checking due to my lack of experience, despite having help and my best efforts)
Download: (private)

**Comment by lordcreeper01** [comment]
Hi! I just took a looj at the xml , these are the errros I have found:

`<spawns>
    <spawns kit="spawn">
        <spawn team="pink" yaw="180"><cylinder base="0.5,59,132.5" radius="3" height="0"/></spawn>
        <spawn team="blue" yaw="0"><cylinder base="0.5,59,-131.5" radius="3" height="0"/></spawn>
    </spawns>
    <default yaw="-90"><cylinder base="0.5,75,0.5" radius="3" height="0"/></default>
</spawns>`

In newer protos the yaw must be defined in <regions> also you seem to have closed twice </spawns> (one before default and one after).

`   
   <apply enter="blue-only" block="never" region="blue-spawn"/>
   <apply enter="pink-only" block="never" region="pink-spawn"/>
   <apply block-break="iron-only" block="never" message="You may only break iron in the base." region="blue-spawn">
   <apply block-break="iron-only" block="never" message="You may only break iron in the base." region="pink-spawn">    
    </apply>
`
On the <regions> module you seem to have applied 2 things to the same regions, if you look at the "block" action there is a "never" and a block-break="iron-only" both of these conflic with each other as block refer to both breaking and placing while block-break is only breaking

`   <apply block="no-void" message="You may not modify the void area.">
        <region>
            <rectangle id="main-area" min="-110,-177" max="112,178"/>
        </region>
    </apply>
    </apply>
`
Here you have 2 closing </apply> :p 

Here is the fixed XML so you can check it out https://gist.github.com/lordcreeper01/7a2df4c7f667846dbce81105f6101390
-Equus

**Comment by Antnecb** [comment]
Ah, I see where I went wrong. Thank you for fixing it!
