### ISSUE TITLE
[MMT][CTW]Puyt

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#58]
### Puyt

"_So, I've been really inactive. Like really inactive. And I saw the competition. So was like meh, lets upload this thing (which I hadn't already). So here it is..._" - Obelistics 2017

![overview](https://cloud.githubusercontent.com/assets/12532048/25719105/3b2751a0-3100-11e7-8c1e-420d5f8dae69.png)

Puyt is a 16v16 CTW which I've had hanging around up to this point. It features two arrow spawners, a golden apple spawner and two wools for each team. There are defence supplies and a limited amount of iron is available throughout the map. Hope you enjoy!

[Images](http://imgur.com/a/kf4B6)  
[Download](https://www.dropbox.com/s/k4stv0m0shjdaf0/Puyt.zip?dl=0)

**Comment by amactus** [comment]
Please provide a non-mediafire download link.

**Comment by sausage191181** [comment]
**Update**

Download link changed to a Dropbox link instead of a MediaFire link.
