### ISSUE TITLE
Insanihe (DTM)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#6]
Insanihe. Insane, huh. A mini DTM by me, with 2 monuments per team. Limited blocks, but iron. Good fun if you're winning. Less so if you're not.

Images: [http://imgur.com/a/CI9IM](url)

Download: [http://www.mediafire.com/file/qk41svugz5o577h/Insanihe.zip](url)

**Comment by amactus** [comment]
After reviewing this map, we've found that is way to small to be taken into consideration for being added. If you would be willing to maybe double it's size, we might consider adding it

Thanks for submitting!

**Comment by amactus** [comment]
Currently, this map is too small for public play. If you'd be willing to remake it, we may consider adding it, but as of now, it won't be added.
