### ISSUE TITLE
[MMT] [DTM] Mijuku

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Map-Rotations#63]
i needed a name so i just went with the first thing i thought of and it ended up being a love live reference

Hello, welcome to my MMT competition map. For this map, I wanted to make something reminiscent of some of the older mini-DTM maps (i.e. Warlock, Snowy Wars), both in terms of gameplay and aesthetics. Players spawn with 7 gold nuggets, which can either be used to upgrade their armor (default leather), or craft golden apples (players spawn with 8 apples). Each team has an enchant table, and there is coal ore underground for xp. Additionally, there are several chests that contain exp bottles and more gold nuggets. As kill rewards, players get 2 gold nuggets, one exp bottle, and 8 arrows, and every second kill get a gapple. With the exception of the axe and shovel, all spawn gear is enchanted. While players spawn with an iron pickaxe, there are 3 diamond pick spawners in the center of the map, putting emphasis on mid control in order to win. The monuments are located in the fort in the corner of each team's side. After 20 minutes, the monument changes to emerald blocks.

![2017-05-13_22 21 05](https://cloud.githubusercontent.com/assets/26776253/26036063/e7e111dc-38a4-11e7-91e5-a21b7d02a47e.png)

Team size: 14v14
Teams: Red vs Blue

[Album](http://imgur.com/a/vxh1n)
[XML](https://gist.github.com/Antnecb/3830073312c605c8d76b63e532212e2f)
Download (private)

**Comment by Palmidence** [comment]
Who currently has the Download? @3Each?

**Comment by Antnecb** [comment]
Updated name in XML gist, use that instead of XML included in download.
