### ISSUE TITLE
[MMT] [Blitz] Boat Blitz

### ISSUE THREAD

**Issue by Ensix** [StratusNetwork/Map-Rotations#65]
### Boat Blitz

A 10 vs. 10 blitz map where instead of attacking the enemy players directly, one must shoot the boats that they're sitting in, causing them to fall into the void

[Images](http://imgur.com/a/uAAP8)  
[Download](https://cdn.discordapp.com/attachments/261928122193018880/313381568406224906/Boat_Blitz.zip)

**Comment by sausage191181** [comment]
Am really loving this idea! Love to see this in-game!
