### ISSUE TITLE
[MMT] [CTW] Ender-fortress

### ISSUE THREAD

**Issue by mrcookieunderscore13** [StratusNetwork/Map-Rotations#68]
Ender-Fortress

An ender-themed CTW map where the you must journey to the other team's wool room in order to place the wool. (you start with wool)
download:
https://www.dropbox.com/s/tjw5hj4fj8tnwlv/Ender-Fortress.zip?dl=0

![2017-05-14_16 28 05](https://cloud.githubusercontent.com/assets/28692086/26037876/257854a8-38cb-11e7-8826-da3ee0b1e314.png)
![2017-05-14_17 28 31](https://cloud.githubusercontent.com/assets/28692086/26037877/257b879a-38cb-11e7-94f3-f05bf1ae4a78.png)
![2017-05-14_17 28 40](https://cloud.githubusercontent.com/assets/28692086/26037878/25813708-38cb-11e7-9728-f89d57e6c549.png)
![2017-05-14_17 29 24](https://cloud.githubusercontent.com/assets/28692086/26037879/2583c7c0-38cb-11e7-8826-c176a3f21de7.png)

**Comment by Palmidence** [comment]
Please provide images for your map.

Also, the use of Mediafire is not allowed, please use Dropbox or Google Drive instead.

**Comment by mrcookieunderscore13** [comment]
ok
