### ISSUE TITLE
Hallcrest (KotF)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#7]
Yeah. King of the Flag is a thing. 3 Spawn Points for the flag, PvP and jump pads. Nothing could possibly go wrong right? Made by Jadsaa and myself.

Images: [http://imgur.com/a/uqp5I](url)

Download: [http://www.mediafire.com/file/b24xw6as4s794ao/Hallcrest.zip](url)

**Comment by Palmidence** [comment]
Tested, it was very fun. I made minor adjustments to the player size, if that's okay, and lowered the limit required to yield a match win.

**Comment by sausage191181** [comment]
Yep all good!
