### ISSUE TITLE
[MMT][CTW] Three Choices

### ISSUE THREAD

**Issue by therealsammyboo** [StratusNetwork/Map-Rotations#71]
This is a CTW where your choices at spawn will influence the rest of the game. You can choose to spawn near iron, near defences, or directly in the wool room.

The XML is not working, nor is block 36 right now, which means that regions and teleportation are broken unfortunately.

https://drive.google.com/open?id=0B3NkEQD9lqkXRU91Q0w5OGhLaTQ
![webp net-resizeimage](https://cloud.githubusercontent.com/assets/28706986/26062260/ac5af392-39cd-11e7-9405-a2d85ede195a.png)

**Comment by ItzaMeLuigi** [comment]
Updated XML: https://pastebin.com/WSHTZqtX
