### ISSUE TITLE
[MMT][Koth][Fly][Rage] -- Xyth II King --

### ISSUE THREAD

**Issue by Tywnis** [StratusNetwork/Map-Rotations#72]
Xyth II King

This is a Koth, using Rage and the Fly module.
There are 27 hills, the 3 central ones give a lot more points. 

This is the 2nd iteration of the Xyth map series - the 1st version was played on OCN, this one has never been loaded publicly. 

[Dropbox link](https://www.dropbox.com/sh/5xl56hz3ovdrjgp/AABWipvVc3Uu6LzbPBTSSeOAa?dl=0)

![image 1](https://cloud.githubusercontent.com/assets/4369123/26062682/21a390a6-39be-11e7-93f8-29fd7b3f9417.png)

**Comment by ArmyFrog** [comment]
It's unique. The palate...reminds my of a worn out door mat.
