### ISSUE TITLE
[MMT][CTW] The Hills

### ISSUE THREAD

**Issue by Kezug0** [StratusNetwork/Map-Rotations#74]
The Hills

"The Hills" is a 16v16 CTW map. I wanted to try something different and that's what came out: 
- the woolrooms are on the two hills which are located at the edge of the map
- the spawns are located below the woolrooms
- players can leave and enter their spawn by entering the portals
    -8 Portals in total
- killrewards are 16 arrows and a golden apple
-

[Images] https://gyazo.com/collections/125db9fb879dcd70abdb0241ceb12816  
[Download] https://www.dropbox.com/s/76x8uu0y8ihmc3p/The%20Hills.zip?dl=0

NOTE: first time I worked with XML -> can't guarantee everything'll work as it should

**Comment by BGMP** [comment]
Please provide a _Dropbox_ or _Google Drive_ download. Mediafire is not allowed.
