### ISSUE TITLE
[MMT][CTF]Campgrounds

### ISSUE THREAD

**Issue by Claph** [StratusNetwork/Map-Rotations#75]
### Campgrounds

Inspired by the quake map, The Campgrounds, here's a CTF take on the map.

[Images]https://imgur.com/a/yo9PI
[Download]https://www.dropbox.com/s/hmjj72eesqdnnnl/Campgrounds.zip?dl=0

**Comment by triplezko** [comment]
https://drive.google.com/file/d/0By5kmnKU1xAOTFBxNGY4Yk9FMDg/view

**Comment by Claph** [comment]
https://www.dropbox.com/s/hmjj72eesqdnnnl/Campgrounds.zip?dl=0 <<<< Use this link instead

**Comment by ArmyFrog** [comment]
Nice typo in your image album
