### ISSUE TITLE
[MMT][DTM] Pond

### ISSUE THREAD

**Issue by Claph** [StratusNetwork/Map-Rotations#76]
### Pond

Lots of them waters and structures and boating and ponds and rocks and frogs and gold and

[Images]https://imgur.com/a/LFmO9 
[Download]https://www.dropbox.com/s/w2rusrjvbva6bz9/Pond.zip?dl=0

**Comment by 3Each** [comment]
Please use a dropbox or google drive link instead of a mediafire link (on both your maps).

**Comment by triplezko** [comment]
https://drive.google.com/file/d/0By5kmnKU1xAOODFZci1WWGJoSmc/view

**Comment by Claph** [comment]
https://www.dropbox.com/s/w2rusrjvbva6bz9/Pond.zip?dl=0 <<<<<< Use this link instead
