### ISSUE TITLE
[DTM/C] Totem

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#79]
### Totem
_By Obelistics and rockymine_

![topdown](https://cloud.githubusercontent.com/assets/12532048/26412816/de3c489a-40a1-11e7-9d4b-348fc282484a.png)

A DTM/C by myself and rockymine. 26 v 26 players. Each team has 1 core and 1 monument. Iron at spawn. Defence chests at each monument. Endstone, Gold and Glass modes for the core. Golden apple kill reward. Leather helmet, chestplate and boots for spawn. And trees. Lots of trees.

[Trailer](https://www.youtube.com/watch?v=wJmQZ_RkNIg)
[Images](http://imgur.com/a/QrpXM)  
[Download](https://www.dropbox.com/s/28gmd009u0b5ptn/Totem.zip?dl=0)

**Comment by ItzaMeLuigi** [comment]
Fixed some errors in the XML and added it to the repo.

**Comment by rockymine** [comment]
Lots and lots of trees ^ n.
