### ISSUE TITLE
Kaskai CTF (CTF)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#8]
Now you may be wondering why it's named Kaskai CTF, and not just Kaskai. Well, when you make three maps, all the same, but different gamemodes your mind stops coming up with original names.... oh and you need to hold the hill to pick up the flag.

Images: [http://imgur.com/a/mrEYB](url)

Download: [http://www.mediafire.com/file/j8kan5n8jglugpn/Kaskai_CTF_%5BTE%5D.zip](url)

**Comment by Palmidence** [comment]
Look at the other Kaskai for reference in terms of land. I've left a response there as well since it was tested.

**Comment by Palmidence** [comment]
I have a feeling the other version plays better, and I'd like to move forward with that map more.
