### ISSUE TITLE
[CTW] [KotH] Kozan

### ISSUE THREAD

**Issue by Hudsonlovestech** [StratusNetwork/Map-Rotations#82]
**Kagami** _made by Sydiem and HuahwisColdHands_
![fix](https://cloud.githubusercontent.com/assets/28578738/26557421/47d76d40-446f-11e7-8d92-760976a5a037.jpg)

Kagami is a Japanese inspired map specialized for CTW. The map has a center temple and side rings with flags as a battle ground. Each team is stacked with gold blocks to make armor. The first team to capture both wools win!

[**Images With Shaders**](http://imgur.com/a/ufcF4)
 [**Images Without Shaders**](http://imgur.com/a/N1TEg)
[**Download**](https://www.dropbox.com/s/ymlxnu8n9somd01/Kagami.zip?dl=0)

**Comment by Palmidence** [comment]
Could you provide non-shader images, please? ^^

**Comment by Hudsonlovestech** [comment]
**Edit:** Non-shader images have been added

**Comment by BGMP** [comment]
Well, after a lot of feedback the map has evolved and certainly changed from what I can see in the images provided. It has been tested multiple times and people seem to like it a lot more than it's original version. I personally find it a new concept, and it worked very well for little matches of 8 to 10 people each team. It has been added to the repo!
