### ISSUE TITLE
Add Jactus to the Rotations

### ISSUE THREAD

**Issue by Stoudyo** [StratusNetwork/Map-Rotations#86]
Hello,
I want to add Jactus in rot because its a good map.
Jactus plays relatively well and doesn't tend to stalemate for too long - there's a good balance of defence and rusher prevention. And it got #3 in the comp . Players appeared to really like Jactus when it was tested during the competition

**ItzaMeStoudyo**

**Comment by BGMP** [comment]
The map has been added to the rotations!
