### ISSUE TITLE
[CTW][TE]Mono 2

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#87]
### Mono 2
**_by Obelistics_**

An **8v8** intended for the upcoming tournament. Based off my previous 5v5 map, Mono. XML should be fully functional and ready to load and play.

**Features:**

- 2 iron islands, with knockback sticks

- A golden apple spawner at mid

-  An arrow spawner on each team's side

- 4 chests of defence materials, and 2 double chests of blocks per side

[Images](http://imgur.com/a/4WaXo)  
[Download](https://www.dropbox.com/s/eboplca1oi99ccz/Mono%202.zip?dl=0)

**Comment by Dqrkshine** [comment]
Imo this map needs more structures and detail. As I see it the islands only have this random block pattern on the floor aswell as some other things. It'd be cool if you could add some structure-ish thing that might fit well to the map aswell as maybe put some more detail in the map.

**Comment by ItzaMeLuigi** [comment]
The map has been loaded on the tournament server for testing.
