### ISSUE TITLE
[DTM] Ants DTM 

### ISSUE THREAD

**Issue by RuedigerLP** [StratusNetwork/Map-Rotations#88]
This is a DTM map based on a simple giant block theme. Players shall feel like little ants working in a giant world.

The xml is not working and incomplete.

Please assign BGMP00.

[Images](http://imgur.com/a/ecWKk)  
[Download]Private

**Comment by BGMP** [comment]
The map was tested multiple times and all the feedback was taken into account to improve it. It played very well and it's now in the repo!
