### ISSUE TITLE
[CTW] Desert Country over Desert Country

### ISSUE THREAD

**Issue by OCNsOMEN** [StratusNetwork/Map-Rotations#89]
Desert Country over Desert Country is a Desert Country edit. Desert Country was in the OCN rots for some months and it's in the Stratus rots at the moment. I saw a x over x map edit some days ago and thought it would be funny to do the same with Desert Country. There are now 4 woolrooms on each side. I changed the team sizes to 26vs26 (overfill= 30vs30). Players aren't able to enter the upper spawn.

[Images] http://imgur.com/a/nMPh6
[Download] https://www.dropbox.com/s/l2jyosovuo0ky8r/Desert%20Country%20over%20Desert%20Country.zip?dl=0

**Comment by Dqrkshine** [comment]
Don't really like this. It's weird with 2 different layers. I know it might make unique gameplay but think of it. The map is doubbled the size now which will require alot more players. Also don't think it will have very good gameplay.

**Comment by OCNsOMEN** [comment]
@Dqrkshine I didn't build it to get into the rots or to be played very often. Just thought it could be a fun map to sn sometimes :P

**Comment by Palmidence** [comment]
The novelty was just there for Sunrise over Paradise, we're not adding more maps that follow the same formula. If there comes a time though that we'll use it, feel free to keep it here.
