### ISSUE TITLE
[KotH] Cavern

### ISSUE THREAD

**Issue by ArmyFrog** [StratusNetwork/Map-Rotations#90]
### Cavern

Cavern is a unique version of runners and defenders that require the runners to run around a run up a ring spiraling up, while the defenders try to shoot them down from the center. As the runners run up the map, the theme changes, going from a lava cave, to a stone cave, to a dirt cave, and eventually the surface. There are various structures and formations creating a very scenic run to the top. At the top there is a small capture point for the runners to capture in order to win. Please note that all magma blocks have been replaced for 1.9 support. The map is subsequentially be updated as soon as they are supported.

[Album](http://imgur.com/a/hIty1)  
[Download](https://cdn.discordapp.com/attachments/207891049828319232/324059417395986432/Cavern.zip)

**Comment by BGMP** [comment]
Almost no xml errors at all. The map was tested and people seem to like it quite a lot. It still might need some few things, but the map itself is done and now in the repo. Well done!

**Comment by ArmyFrog** [comment]
[Download](https://github.com/StratusNetwork/Map-Rotations/files/1103555/Cavern.zip)
Updated map content
