### ISSUE TITLE
[CTW][TE]Bounding Deep

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#91]
### Bounding Deep
**_By Obelistics_**

![overview](https://user-images.githubusercontent.com/12532048/27144909-84c5aae6-512b-11e7-9c79-8c9792191588.png)

This is an 8v8 CTW created for the use in upcoming tourneys (specifically this one if possible). It features 4 wools (2 per team), and 4 arrow spawners and 1 gapple spawner.

[Images](http://imgur.com/a/ozQI9)  
[Download](https://www.dropbox.com/s/4s3k4ot5tzbpsme/bounding_deep.zip?dl=0)

**Comment by Dqrkshine** [comment]
Loooks nice!

+1

**Comment by ItzaMeLuigi** [comment]
The map has been loaded on the tournament server for testing.
