### ISSUE TITLE
[CTW] Ski Trip to Blizzardtown

### ISSUE THREAD

**Issue by master00ofdsiware** [StratusNetwork/Map-Rotations#93]
### Ski Trip to Blizzardtown
`by _DISTRACTION_`

![](http://i.imgur.com/stjF7Ig.png)

This ski-slope themed CTW, with 32 vs 32 team sizes, is the Christmas version of Trip to Acidtown. It was loaded on the Overcast Network and put into the Capture1 rotations during the holiday rotations of 2016.

[Images](http://imgur.com/a/Sbkzc)  

For the time being, I would like this map to remain exclusive to Stratus. As such, I request that a map developer message me on Discord at Ale#2218 in order to obtain the packaged download.

During my tenure as a Builder on the Overcast Network, I perfected this map's XML, and had it loaded into the repository, meaning that it is pruned and the map.png is of the correct size. _The data folder is **necessary** for the map to work properly, and should be kept; it is not a mistake._

**Comment by 2000thehecf1** [comment]
It isn't in the public server repo though @Palmidence 

![captura](https://user-images.githubusercontent.com/11505855/27445341-ab93f494-5779-11e7-9ac0-6a237b2b39f5.PNG)

**Comment by Palmidence** [comment]
It is, try doing /newmaps :)

**Comment by 2000thehecf1** [comment]
I have no permissions and still I can't set it :(

**Comment by Palmidence** [comment]
![image](https://user-images.githubusercontent.com/17485345/27482130-24658292-57ee-11e7-8cac-b25d0ce1cb6b.png)
