### ISSUE TITLE
[DTM/DTC] Dam Nation

### ISSUE THREAD

**Issue by reidbhuntley** [StratusNetwork/Map-Rotations#96]
### Dam Nation

![Dam Nation](http://i.imgur.com/qR0WoGt.png)

A hybrid Destroy the Monument/Core map, built for matches of 24 vs. 24. Each team has two obsidian monuments -- one per team at the Dam and at the Fort -- as well as an obsidian core near their spawn. Teams must decide to either defend aggressively at their monuments on the front lines, or fall back and protect their core. After 30 minutes have passed, the core changes into gold blocks, and after 45 minutes it changes once more into sponge blocks, which will (hopefully!) reduce stalemates.

[Album](http://imgur.com/a/pmCyv)
[Download (1.2.0)](https://www.dropbox.com/s/wap12y8g5rzoj0j/Dam%20Nation%20v1.2.0.zip?dl=0)

**Comment by Palmidence** [comment]
Wouldn't a gold block be faster to break than a sponge? :thinking:

**Comment by reidbhuntley** [comment]
> Wouldn't a gold block be faster to break than a sponge? 🤔

Gah, you're right! I've uploaded a patch that uses coal blocks rather than gold blocks as the first core mode.

**Comment by Palmidence** [comment]
Sounds a lot better! 😸 

Anyways, this is really a fantastic map design. Really interested in it! Good job.

**Comment by ArmyFrog** [comment]
This map has such a hilarious pun. Probable because it literally uses the letters of the word instead of just the sounds, and the two words match the theme of the map so much. Great job!

**Comment by PoseidonsM** [comment]
We've updated the XML for your map (fixing regions and some other minor problems). We'll get to testing it soon, and we'll try to message you when we do. Just for any further updates here is the fixed XML, so please replace it in your folder.

[xml.zip](https://github.com/StratusNetwork/Map-Rotations/files/1117750/xml.zip)

P.S. Please see http://docs.stratus.network/guides/regions when doing regions for your future maps.

**Comment by PoseidonsM** [comment]
I tested this once today. Could you please make the following revisions:
- Indication of where monuments/core is by a sign of some description in the sky (or a beacon)

We'll also update the spawnkit to this in the next revision if you're happy with it (also replacing the potion to have the speed texture)
<img width="415" alt="screen shot 2017-07-03 at 8 07 53 pm" src="https://user-images.githubusercontent.com/7067991/27788293-6a8fea92-602b-11e7-874f-e23529d79b14.png">

**Comment by reidbhuntley** [comment]
Apologies for the late response -- I was away on a camping trip for a week.
I've made an update with the changes you've requested. Feel free to add in your suggested kit to the XML.

**Comment by PoseidonsM** [comment]
Map looks good and we'll consider it for a future rotation update, for any further contact we'll message you on discord. 😄

Here's another updated map.xml ([xml.zip](https://github.com/StratusNetwork/Map-Rotations/files/1144908/xml.zip))
Also, please do read http://docs.stratus.network/guides/regions because your updated core regions were slightly off again: you can't use world edit coordinates when doing regions!
